name: build Smakolik.Bot solution
on:
  push:
    branches: [ main ]
  pull-request:
    branches: [ main ]
jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        
      -
      