name: build Smakolik.Bot solution


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
        
      - name: Build SmakolikBot
        shell: bash
        run: |
          dotnet restore "SmakolikBot.sln"
          cd SmakolikBot
          dotnet build --no-restore